### PR TITLE
Allow skipping compile commands and prompt spam

### LINKED ISSUE #1: Don't always prompt for how to handle missing compile_command.json
Hi, thank you for writing this plugin. Works great. I have one issue though. When I open a C file without a ``compile_commands.json`` being present, I get always prompted, which is annoying. Can you implement a way to turn that off or only print a small notification in the status line?

### PR DESCRIPTION
**Pull request by asmodeus812**
Fixes https://github.com/asmodeus812/coc-sonarlint/issues/1

### CODE REVIEW

**Comment by jclsn** [comment]
Thanks for working on this so quick! Anyway I can test this?

**Comment by asmodeus812** [comment]
@jclsn there is a quick way to test this, you can either try to clone the repo in `.config/extensions/node_modules` and run `npm install` there, we did add something in coc.nvim recently which might allow you to simply do `CocInstall https://github.com/asmodeus812/coc-sonarlint`

I can publish it but it would be better if you can test it first to verify this is the behaviour you are looking for.

**Comment by jclsn** [comment]
I tried that. npm install fails for me in both cases

```
❯ npm install
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: coc.nvim@0.0.83-next.18
npm error Found: @types/node@14.18.63
npm error node_modules/@types/node
npm error   dev @types/node@"^14.14" from the root project
npm error   @types/node@"*" from @types/fs-extra@8.1.5
npm error   node_modules/@types/fs-extra
npm error     dev @types/fs-extra@"^8.0.0" from the root project
npm error   1 more (@types/glob)
npm error
npm error Could not resolve dependency:
npm error peer @types/node@"^16.18.0" from coc.nvim@0.0.83-next.18
npm error node_modules/coc.nvim
npm error   dev coc.nvim@"^0.0.83-next.17" from the root project
npm error
npm error Conflicting peer dependency: @types/node@16.18.97
npm error node_modules/@types/node
npm error   peer @types/node@"^16.18.0" from coc.nvim@0.0.83-next.18
npm error   node_modules/coc.nvim
npm error     dev coc.nvim@"^0.0.83-next.17" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/jan/.npm/_logs/2024-05-25T08_03_30_253Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/jan/.npm/_logs/2024-05-25T08_03_30_253Z-debug-0.log
```

What I am looking for is a simple notification of the missing ``compile_commands.json`` file in the status bar without any prompt. I also don't think that the option to autogenerate the ``coc-settings.json`` makes much sense. For me it genertated that in the project root directory and suddenly I had a hidden folder there that was added to my version control by mistake. The user should configure the plugin manually as provided by the readme.

**Comment by asmodeus812** [comment]
Just add --legacy-peer-deps this to npm install, it should build in that case.

At the moment the prompt will be shown only once the first time you open the project, select do not show this again. Keep in mind that sonar does need a valid compile commands to correctly verify your project, otherwise what you see are generic common ruleset

**Comment by jclsn** [comment]
Yeah that worked. 

I have to say that I still dislike the current solution. I will be prompted for every C file I open and the plugin needs to keep a list of workspaces to ignore. 

I think it would be better to just not load sonarlint-ls when not ``compile_commands.json`` is found. Other coc plugins print some messages to the airline status bar as shown here

image

This is much less distracting and doesn't require user interaction every time you open some new random file that is not located in a workspace.

**Comment by asmodeus812** [comment]
I think you have not correctly built the extension, or coc is loading the old one. The modified behviour will not ask for each file, it is just once, once until you say `do not prompt me again` then it will not prompt you again for the current project. The workspace specific config is stored in `.config/coc/memos.json`. List your coc extensions and check what version is loaded, is it 0.0.10 or something else.

**Comment by jclsn** [comment]
This is what I am getting

``` 
SonarLint might be unable to analyze C and C++ file(s) because there is no configured compilation database.
(1)Configure compile commands now, (2)Ask me later to configure compile commands, (3)Do not ask for compile commands again for this workspace: 
```

and it prompts me again in other workspaces.

It would also be nicer if it looked like this, which is easier to read

```
SonarLint might be unable to analyze C and C++ file(s) because there is no configured compilation database.
1. Configure compile commands now
2. Ask me later to configure compile commands
3. Do not ask me again for this workspace
4. Never ask me again
```

**Comment by asmodeus812** [comment]
Could you first verify you are loading the 0.0.10 version first  ? Secondly what do you mean by workspace ? It will prompt you only once for new workspaces. Also try to set this in your coc-settings - sonarlint.notifyMissingCompileCommands: false to never get prompted again.

**Comment by jclsn** [comment]
There is nothing in here about the version

```
❯ cat .config/coc/memos.json
{
  "coc-json|global": {
    "json-schema-cache": {
      "http://json.schemastore.org/prettierrc": {
        "etag": "\"80e08ca9849bd81:0\"",
        "fileName": "b2ed7a7b6c79e58baf94e4ce160282de.schema.json",
        "updateTime": 1692622323086
      },
      "https://json.schemastore.org/package.json": {
        "etag": "\"0dac66160d0d91:0\"",
        "fileName": "473f72b44c2905902dfbcc770aab7f7a.schema.json",
        "updateTime": 1692622323412
      },
      "https://json.schemastore.org/semantic-release.json": {
        "etag": "\"808cdec3a9a4d81:0\"",
        "fileName": "fbc95702ba6eddb3e2de4f52e31ca82a.schema.json",
        "updateTime": 1692622324101
      },
      "https://json.schemastore.org/ava.json": {
        "etag": "\"80cdbd40989d91:0\"",
        "fileName": "635f57185b22bce9d3a56c68f5da4ad7.schema.json",
        "updateTime": 1692622324110
      },
      "https://json.schemastore.org/jscpd.json": {
        "etag": "\"80bec5ba1984d81:0\"",
        "fileName": "22bfc1ab1ff56aae62322f6ce45dab5a.schema.json",
        "updateTime": 1692622324113
      },
      "https://json.schemastore.org/stylelintrc.json": {
        "etag": "\"0d52dd6eabd91:0\"",
        "fileName": "000bfbdd14d2fb8ec5b0d59bec32ef98.schema.json",
        "updateTime": 1692622324119
      },
      "https://json.schemastore.org/prettierrc.json": {
        "etag": "\"80e08ca9849bd81:0\"",
        "fileName": "ea5ab10330a3ab77dfd6d00a735b0925.schema.json",
        "updateTime": 1692622324133
      },
      "https://json.schemastore.org/eslintrc.json": {
        "etag": "\"09c10cf5f2bd91:0\"",
        "fileName": "c5064f140d4cfdbf4d6fbe68f68abbb1.schema.json",
        "updateTime": 1692622324135
      },
      "https://json.schemastore.org/web-manifest-combined.json": {
        "etag": "\"9256526360d0d91:0\"",
        "fileName": "b06e2f702dd4972ea2bb3d76ff088406.schema.json",
        "updateTime": 1700321220008
      },
      "https://json.schemastore.org/foxx-manifest.json": {
        "etag": "\"0ad956060d0d91:0\"",
        "fileName": "5e1deef4adbcb453011b95df734ed4a0.schema.json",
        "updateTime": 1700321220010
      },
      "https://json.schemastore.org/webextension.json": {
        "etag": "\"07f86260d0d91:0\"",
        "fileName": "b731fe11a3d127fd02a39912a2530816.schema.json",
        "updateTime": 1700321220012
      },
      "https://json.schemastore.org/web-manifest-share-target.json": {
        "etag": "\"8059190326ad81:0\"",
        "fileName": "cdeb8e92350ff78b8eec26631dae6f2d.schema.json",
        "updateTime": 1700321220684
      },
      "https://json.schemastore.org/web-manifest-app-info.json": {
        "etag": "\"b27da80326ad81:0\"",
        "fileName": "37e25b60beaa201ec2222b96a2ea00d6.schema.json",
        "updateTime": 1700321220688
      },
      "https://json.schemastore.org/web-manifest.json": {
        "etag": "\"8059190326ad81:0\"",
        "fileName": "6edb6ea4435d040104641056c40c6326.schema.json",
        "updateTime": 1700321220701
      },
      "https://json-schema.org/draft-07/schema": {
        "etag": "\"673ab193658a160ca86fe1c7b20d51d9\"",
        "fileName": "84af290a1dfc2be2aa95724d3556c0ee.schema.json",
        "updateTime": 1710680956993
      }
    }
  },
  "coc-rust-analyzer|global": {
    "release": "2023-10-16"
  },
  "coc-sonarlint|/home/jan/Workspace/C": {
    "doNotAskAboutCompileCommands": true
  }
}
```

Furthermore CoC is telling me that ``"sonarlint.notifyMissingCompileCommands": false`` is not allowed.

**Comment by jclsn** [comment]
Oh yeah the version is ``"coc-sonarlint": ">=0.0.9"``. I did pull the above branch though.

**Comment by jclsn** [comment]
I pulled and ran ``npm install`` again. It now recognizes the setting and it works. For me this is fine now.

**Comment by asmodeus812** [comment]
Okay i did some more changes, now there is a fourth option which will add the config to the global coc-settings, the 3rd option will disable only for the current workspace.

**Comment by jclsn** [comment]
Great! Ship it!

**Pull request merged**
